routes/web.php
<?php

declare(strict_types=1);

use App\Enums\Role;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\LogsController;
use App\Http\Controllers\PasswordResetLinkController;
use App\Livewire\SettingsForm;
use App\Livewire\UserForm;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Features;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', static fn () => view('application.create'));
Route::get('/bulletin-adhesion-pdf', static fn () => redirect('/BulletinAdhesion.pdf'));
Route::get('/success', static fn () => view('application.success'))->name('success');

Route::get('/archives', static fn () => view('application.archives'))
    ->name('archives')
    ->middleware(['auth', 'role:'.Role::BOARD->value]);

Route::prefix('admin')
    ->middleware(['auth', 'role:'.Role::ADMIN->value, config('jetstream.auth_session'), 'verified'])
    ->group(static function (): void {
        Route::get('', static fn () => view('admin.index', ['ref' => base_path().'/.git/refs/heads/main']))->name('admin.index');

        Route::prefix('logs')->group(static function (): void {
            Route::get('', LogsController::class)->name('admin.logs');
        });

        Route::prefix('users')->group(static function (): void {
            Route::get('', UsersController::class)->name('admin.users');
            Route::get('/edit/{user}', UserForm::class)->name('admin.users.edit');
            Route::get('/create', UserForm::class)->name('admin.users.create');
        });

       Route::get('/settings', SettingsForm::class)->name('admin.settings');
    });

Route::prefix('dashboard')
    ->middleware(['auth', 'role:'.Role::BOARD->value, config('jetstream.auth_session'), 'verified'])
    ->group(function (): void {
        Route::get('', \App\Livewire\Dashboard\Dashboard::class)
            ->name('dashboard.index')
            ->middleware(['auth', 'role:'.Role::BOARD->value]);

        Route::prefix('application')->group(function (): void {
            Route::get(
                'complete/{application}',
                \App\Livewire\ApplicationComplete::class
            )->name('dashboard.application.complete')
                ->middleware(['auth', 'role:'.Role::TREASURY->value]);
        });
});

if (Features::enabled(Features::resetPasswords())) {
    // Overwrite the forgot-password post route to add enumeration protections
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
        ->middleware(['guest:'.config('fortify.guard')])
        ->name('password.email');
}

app/Livewire/Application/Element.php
<?php

declare(strict_types=1);

namespace App\Livewire\Application;

use Livewire\Component;

final class Element extends Component
{
    public string $title;
    public string $content;
}

app/Livewire/ApplicationComplete.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Enums\ApplicationStatus;
use App\Models\Application;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Support\Facades\Log;
use Livewire\Component;

final class ApplicationComplete extends Component
{
    use HasTextFields;

    public Application $application;

    /**
     * @throws AuthorizationException
     */
    public function complete(): void
    {
        $this->validate();

        $this->authorize('complete', Application::class);
        $this->application->status = ApplicationStatus::COMPLETED;
        $this->application->update();
        Log::notice("Application {$this->application->id} completed.");

        redirect(route('dashboard.index'));
    }

    /**
     * @return array<string, array<int, ValidationRule|string>>
     */
    public function rules(): array
    {
        return [
            'application.first_withdrawal_date' => [ApplicationForm::REQUIRED_IF_SEPA, 'nullable', 'date', 'after_or_equal:tomorrow'],
        ];
    }
}

app/Livewire/ApplicationForm.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Enums\ContributionWay;
use App\Models\Application;
use App\Rules\Iban;
use App\Services\SireneAPI;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Enum;
use Livewire\Attributes\On;
use Livewire\Component;
use SolidairesInformatique\BadParameter;
use SolidairesInformatique\ClientException;
use Spatie\Honeypot\Http\Livewire\Concerns\HoneypotData;
use Spatie\Honeypot\Http\Livewire\Concerns\UsesSpamProtection;

final class ApplicationForm extends Component
{
    use ConvertEmptyStringsToNull;
    use HasRateLimit;
    use HasTextFields;
    use UsesSpamProtection;

    public Application $application;
    public bool $employee = true;
    public bool $minimalContribution = false;
    public ?string $wage = '';
    public float $contributionPercentage = 0.5;
    public bool $terms = false;
    public int $step = 1;
    public bool $noSiret = false;
    private SireneAPI $sireneAPI;
    public HoneypotData $extraFields;

    private const string SIRET_FIELD = 'application.company_siret';
    public const string REQUIRED_IF_SEPA = 'required_if:application.contribution_way,'.ContributionWay::SEPA->value;

    public function boot(SireneAPI $sireneAPI): void
    {
        $this->sireneAPI = $sireneAPI;
    }

    public function mount(): void
    {
        $this->extraFields = new HoneypotData();

        if (request()->query->has('SIRET')) {
            $this->application->company_siret = (string) request()->query->get('SIRET');
            $this->updated(self::SIRET_FIELD);
        }
    }

    /**
     * @return array<string, mixed>
     */
    protected function rules(): array
    {
        return array_merge(...$this->rulesByStep());
    }

    public function updated(string $propertyName): void
    {
        $this->validateOnly($propertyName);

        if ($propertyName === 'wage' || $propertyName === 'minimalContribution') {
            $this->updateContribution();
        }

        if ($this->noSiret === false && $propertyName === self::SIRET_FIELD) {
            $this->updateCompanyWithSiret();
        }
    }

    public function next(): void
    {
        $this->validate($this->rulesByStep()[$this->step]);

        if ($this->step === 2) {
            $this->updateSepaPrefill();
        }

        ++$this->step;
    }

    public function back(): void
    {
        --$this->step;
    }

    /**
     * @throws \Exception
     */
    public function submit(): void
    {
        $this->protectAgainstSpam();
        $this->validate();

        if ($this->triedLessThanAMinuteAgo('send-application:'.request()->getClientIp())) {
            return;
        }

        if (!$this->application->save()) {
            $this->addError('submit', __('validation.server_error'));
            Log::error('validation.server_error');

            return;
        }

        Log::info("Application {$this->application->id} submitted.");
        $this->redirect(route('success'));
    }

    #[On('updateSignature')]
    public function setSignature(string $signature_base64 = ''): void
    {
        $this->application->signature = $signature_base64;
        $this->updated('application.signature');
    }

    public function incrementContribution(): void
    {
        $this->application->contribution = floor($this->application->contribution) + 1;
    }

    /**
     * @return array<int<1, 4>, array<string, array<mixed>>>
     */
    private function rulesByStep(): array
    {
        return
            [
                1 => [
                    'application.name' => self::getTextValidators(true),
                    'application.firstname' => self::getTextValidators(true),
                    'application.address' => self::getTextValidators(true),
                    'application.postcode' => ['required', 'numeric', 'string'],
                    'application.city' => self::getTextValidators(true),
                    'application.email' => self::getTextValidators(true, ['email']),
                    'application.mobile' => self::getTextValidators(true),
                    'application.birth_year' => ['nullable', 'numeric', 'min:1900', 'max:'.date('Y')],
                    'application.gender' => self::getTextValidators(false),
                ],
                2 => [
                    self::SIRET_FIELD => ['nullable', 'digits:14', Rule::requiredIf(fn () => $this->employee && !$this->noSiret)],
                    'application.company_name' => self::getTextValidators(false, [Rule::requiredIf(fn () => $this->employee)]),
                    'application.company_legal_address' => self::getTextValidators(false),
                    'application.company_work_address' => self::getTextValidators(false),
                ],
                3 => [
                    'wage' => ['nullable', 'numeric', 'min:0'],
                    'application.contribution' => ['required', 'numeric', 'min:1'],
                    'application.contribution_way' => ['required', new Enum(ContributionWay::class)],
                    'application.sepa_full_name' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_address' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_postcode' => [self::REQUIRED_IF_SEPA, 'nullable', 'numeric', 'string'],
                    'application.sepa_city' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_country' => [self::REQUIRED_IF_SEPA, 'nullable', 'in:France'],
                    'application.iban' => [self::REQUIRED_IF_SEPA, 'nullable', new Iban()],
                    'application.bic' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA, 'nullable', 'alpha_num']),
                    'application.made_at' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.signature' => [self::REQUIRED_IF_SEPA, 'nullable', 'nullable', 'min:64'],
                ],
                4 => [
                    'application.mail_local' => ['nullable', 'boolean'],
                    'application.applicant_comment' => ['nullable', 'max:500'],

                    'terms' => ['accepted'],
                ],
            ];
    }

    private function updateContribution(): void
    {
        if ($this->minimalContribution) {
            $this->contributionPercentage = 0;
            $this->application->contribution = 1;

            return;
        }

        $this->contributionPercentage = $this->wage <= 1600 ? 0.5 : 0.65;
        $this->application->contribution = max(round((float) $this->wage * ($this->contributionPercentage / 100), 2), 1);
    }

    private function updateCompanyWithSiret(): void
    {
        try {
            $workplace = $this->sireneAPI->getWorkplace((string) $this->application->company_siret);
        } catch (BadParameter $exception) {
            Log::debug($exception->getMessage());
            $this->addErrorToSiretField($exception->getMessage());

            return;
        } catch (ClientException $exception) {
            Log::notice($exception->getMessage());
            $this->addErrorToSiretField($exception->getCode() === 404 ? (string) __('form.siret.404') : null);

            return;
        }

        $this->application->company_name = $workplace->uniteLegale->denominationUniteLegale;
        $this->application->company_work_address = $workplace->adresse->__toString();

        try {
            $headOffice = $this->sireneAPI->getHeadOffice($workplace);
            $this->application->company_legal_address = $headOffice->adresse->__toString();
        } catch (\Throwable $exception) {
            Log::notice($exception->getMessage());
        }
    }

    private function addErrorToSiretField(?string $message = null): void
    {
        $this->validateOnly(
            self::SIRET_FIELD,
            [self::SIRET_FIELD => fn (string $attr, mixed $val, \Closure $fail) => $fail($message ?? __('form.siret.generic'))]
        );
    }

    private function updateSepaPrefill(): void
    {
        $this->application->sepa_full_name = $this->application->name.' '.$this->application->firstname;
        $this->application->sepa_address = $this->application->address;
        $this->application->sepa_postcode = $this->application->postcode;
        $this->application->sepa_city = $this->application->city;
        $this->application->sepa_country = 'France';
    }
}

app/Livewire/ApplicationOverview.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\Application;
use libphonenumber\NumberParseException;
use libphonenumber\PhoneNumberUtil;
use Livewire\Component;

final class ApplicationOverview extends Component
{
    public Application $application;
    public bool $showRestrictedInformation;

    public function mount(): void
    {
        $this->tryToFormatPhone();
    }

    private function tryToFormatPhone(): void
    {
        $phoneNumberUtil = PhoneNumberUtil::getInstance();

        try {
            $number = $phoneNumberUtil->parse($this->application->mobile, 'FR');
            if (
                $phoneNumberUtil->isPossibleNumber($number)
                && $phoneNumberUtil->isValidNumberForRegion($number, 'FR')
            ) {
                $this->application->mobile = $phoneNumberUtil->format($number, \libphonenumber\PhoneNumberFormat::NATIONAL);
            }
        } catch (NumberParseException) {
        }
    }
}

app/Livewire/ConvertEmptyStringsToNull.php
<?php

declare(strict_types=1);

namespace App\Livewire;

/**
 * @source https://github.com/livewire/livewire/issues/823#issuecomment-821074805
 */
trait ConvertEmptyStringsToNull
{
    /**
     * @var string[]
     */
    protected array $convertEmptyStringsExcept = [];

    public function updatedConvertEmptyStringsToNull(string $name, mixed $value): void
    {
        if (!\is_string($value) || \in_array($name, $this->convertEmptyStringsExcept, true)) {
            return;
        }

        $value = trim($value);
        $value = $value === '' ? null : $value;

        data_set($this, $name, $value);
    }
}

app/Livewire/Dashboard/Dashboard.php
<?php

declare(strict_types=1);

namespace App\Livewire\Dashboard;

use App\Enums\OptionEnum;
use App\Livewire\HasPrivateUserProperty;
use App\Models\Option;
use Livewire\Attributes\Title;
use Livewire\Attributes\Url;
use Livewire\Component;

#[Title("Gestion des demands d'adhésions")]
final class Dashboard extends Component
{
    use HasPrivateUserProperty;

    #[Url]
    public string $filter = '';

    public function mount(): void
    {
        foreach ([OptionEnum::UNION_BIC, OptionEnum::UNION_IBAN, OptionEnum::WELCOME_SESSION_LINK] as $option) {
            if (Option::get($option)->value === null) {
                abort(
                    503,
                    \sprintf(
                        "Le paramètre '%s' n'est pas défini. Un·e admin doit se rendre sur %s",
                        __("dashboard.settings.{$option->value}"),
                        route('admin.settings')
                    )
                );
            }
        }
    }
}

app/Livewire/Dashboard/General.php
<?php

declare(strict_types=1);

namespace App\Livewire\Dashboard;

use App\Enums\OptionEnum;
use App\Livewire\HasPrivateUserProperty;
use App\Models\Option;
use Illuminate\Support\Carbon;
use Livewire\Component;

final class General extends Component
{
    use HasPrivateUserProperty;

    public bool $hasEnabledTwoFactorAuthentication;
    public bool $shouldUpdateWelcomeSessionLink;

    public function mount(): void
    {
        $this->hasEnabledTwoFactorAuthentication = $this->user->hasEnabledTwoFactorAuthentication();
        $this->shouldUpdateWelcomeSessionLink = Carbon::parse(Option::get(OptionEnum::WELCOME_SESSION_LINK)->updated_at)->lessThan(now()->subMonths(6));
    }
}

app/Livewire/FlashMessage.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use Livewire\Component;

final class FlashMessage extends Component
{
    public string $message;
}

app/Livewire/HasPrivateUserProperty.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\User;
use Illuminate\Support\Facades\Auth;

trait HasPrivateUserProperty
{
    private readonly User $user;

    public function __construct()
    {
        $user = Auth::user();
        if (!$user instanceof User) {
            throw new \RuntimeException("Couldn't find user.");
        }
        $this->user = $user;
    }
}

app/Livewire/HasRateLimit.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use Illuminate\Support\Facades\RateLimiter;

trait HasRateLimit
{
    private function triedLessThanAMinuteAgo(string $rateLimiterKey): bool
    {
        if (RateLimiter::tooManyAttempts($rateLimiterKey, 1)) {
            $seconds = RateLimiter::availableIn($rateLimiterKey);
            $this->addError('submit', __('validation.throttled_with_seconds', ['seconds' => $seconds]));

            return true;
        }

        RateLimiter::hit($rateLimiterKey);

        return false;
    }
}

app/Livewire/ShowUsers.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Livewire\Component;

final class ShowUsers extends Component
{
    /**
     * @var Collection<int, User>
     */
    public Collection $users;

    public function mount(): void
    {
        $this->users = User::all();
    }
}

resources/views/livewire/application-complete.blade.php
<div>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Finaliser l'adhésion
        </h2>
        <p>
            La finalisation de l'adhésion entraîne l'ajout de la personne dans la base d'adhérent·es et notifie le bureau ainsi que le
            groupe d'accueil.
        </p>
    </x-slot>

    <div class="form__section">
        <p class="form__section__instruction">
            {{ $application->firstname }} {{ $application->name }}
            <span title="{{ $application->id }}" class="font-mono text-xs">{{ $application->getShortenedId() }}</span>
        </p>

        @if($application->contribution_way === \App\Enums\ContributionWay::SEPA)
            <p class="my-2">
                Ces informations seront envoyées dans le mail de bienvenue.
            </p>

            <div class="form__input-group">
                <div class="form__input-group__element">
                    <label class="form__input-group__element__label" for="first_withdrawal_date">
                        Date du premier prélèvement
                    </label>
                    <input
                        wire:model.blur="application.first_withdrawal_date"
                        id="first_withdrawal_date"
                        type="date"
                        required
                        min="{{\Carbon\Carbon::now()->format('Y-m-d')}}"
                        max="{{\Carbon\Carbon::now()->addMonths(2)->format('Y-m-d')}}"
                        class="form__input-group__element__input @error('application.first_withdrawal_date') errored @enderror"
                    >
                    @error('application.first_withdrawal_date') <p class="form__input-group__element__error">{{ $message }}</p> @enderror

                </div>
            </div>
        @endif

        <p class="my-2">
            L'ajout des données dans le CRM n'est pas encore automatisé, il faut le faire manuellement à cette étape.
        </p>

        <input
            wire:loading.attr="disabled"
            wire:click.prevent="complete"
            type="submit"
            class="form__submit @error('submit') form__submit_error @enderror"
            value="{{ __('dashboard.actions.complete') }}"
        >

        <p wire:loading class="inline">
            Sauvegarde en cours…
        </p>

        <p class="my-2">
            Cette étape archive automatiquement le bulletin d'adhésion
            @if($application->contribution_way === \App\Enums\ContributionWay::SEPA) et le mandat SEPA @endif
            en PDF sur le cloud.
        </p>

        <livewire:application-overview :application="$application" :showRestrictedInformation="true" />
    </div>
</div>

resources/views/livewire/application-overview.blade.php
<div class="my-4 px-6">
    <h3 class="font-bold">Bulletin d'adhésion</h3>
    <dl class="grid md:grid-cols-3 grid-cols-2 gap-4 sm:px-6">
        <livewire:application.element
            :title="__('validation.attributes.name')"
            :content="$application->name"
        />
        <livewire:application.element
            :title="__('validation.attributes.firstname')"
            :content="$application->firstname"
        />
        @if($showRestrictedInformation)
            <livewire:application.element
                :title="__('validation.attributes.address')"
                :content="$application->address"
            />
        @endif
        <livewire:application.element
            :title="__('validation.attributes.postcode')"
            :content="$application->postcode"
        />
        <livewire:application.element
            :title="__('validation.attributes.city')"
            :content="$application->city"
        />
        <livewire:application.element
            :title="__('validation.attributes.email')"
            :content="$application->email"
        />
        <livewire:application.element
            :title="__('validation.attributes.mobile')"
            :content="$application->mobile"
        />
        @if($application->birth_year)
            <livewire:application.element
                :title="__('validation.attributes.birth_year')"
                :content="$application->birth_year"
            />
        @endif
        @if($application->gender)
            <livewire:application.element
                :title="__('validation.attributes.gender')"
                :content="$application->gender"
            />
        @endif

        @if($showRestrictedInformation)
        <livewire:application.element
            :title="__('validation.attributes.contribution')"
            :content="number_format($application->contribution, 2, ',', '')"
        />
        <livewire:application.element
            :title="__('validation.attributes.contribution_way')"
            :content='__("form.contribution_way_value.{$application->contribution_way->value}")'
        />
        @endif

        <hr class="md:col-span-3 col-span-2">
        @if($application->company_name || $application->company_legal_address || $application->company_work_address)
            <livewire:application.element
                :title="__('validation.attributes.company_name')"
                :content="$application->company_name"
            />
            @if($application->company_siret)
                <livewire:application.element
                    title="SIRET"
                    :content="$application->company_siret"
                />
            @endif
            @if($application->company_legal_address)
                <livewire:application.element
                    :title="__('validation.attributes.company_legal_address')"
                    :content="$application->company_legal_address"
                />
            @endif
            @if($application->company_work_address)
                <livewire:application.element
                    :title="__('validation.attributes.company_work_address')"
                    :content="$application->company_work_address"
                />
            @endif
        @else
            <livewire:application.element
                :title="__('validation.attributes.company_name')"
                content="Aucune information"
            />
        @endif
        <hr class="md:col-span-3 col-span-2">

        @if($application->applicant_comment)
            <div class="col-span-3">
                <dt class="text-gray-600">{{ __('validation.attributes.comment') }}</dt>
                <dd>{{ $application->applicant_comment }}</dd>
            </div>
        @endif

        @if($application->id !== null)
            <div class="md:col-span-3 col-span-2"></div>
            <livewire:application.element
                title="Liste mail section territoriale"
                :content="$application->mail_local ? 'Oui' : 'Non'"
            />
        @endif
    </dl>

    @if($showRestrictedInformation && $application->contribution_way === \App\Enums\ContributionWay::SEPA)
        <div>
            <h3 class="font-bold mt-8">Mandat SEPA</h3>
            <dl class="grid md:grid-cols-3 grid-cols-2 gap-4 sm:px-6">
                <livewire:application.element
                    :title="__('validation.attributes.full_name')"
                    :content="$application->sepa_full_name"
                />
                <livewire:application.element
                    :title="__('validation.attributes.address')"
                    :content="$application->sepa_address"
                 />
                <livewire:application.element
                    :title="__('validation.attributes.postcode')"
                    :content="$application->sepa_postcode"
                 />
                <livewire:application.element
                    :title="__('validation.attributes.city')"
                    :content="$application->sepa_city"
                 />
                <livewire:application.element
                    :title="__('validation.attributes.country')"
                    :content="$application->sepa_country"
                 />
                <livewire:application.element
                    :title="__('validation.attributes.iban')"
                    :content="$application->iban"
                 />
                <livewire:application.element
                    :title="__('validation.attributes.bic')"
                    :content="$application->bic"
                 />
                <livewire:application.element
                    :title="__('validation.attributes.made_at')"
                    :content="$application->made_at"
                 />
                <livewire:application.element
                    :title="__('form.current_date')"
                    :content="($application->id === null ? now() : $application->created_at)->format('d/m/Y')"
                 />
                <div>
                    <dt class="text-gray-600">{{ __('validation.attributes.signature') }}</dt>
                    <img src="{{ $application->signature }}" alt="" width="150">
                </div>
            </dl>
        </div>
    @endif
</div>

resources/views/livewire/flash-message.blade.php
<div class="mx-auto max-w-xl border m-4 rounded" role="alert" aria-live="assertive" aria-atomic="true" data-mdb-autohide="false">
    <p class="bg-white px-4 py-5 sm:px-6 rounded">
        {{ $message }}
    </p>
</div>

resources/views/livewire/show-application.blade.php
<div class="overflow-hidden bg-white shadow border-2 mb-6 sm:rounded-lg">
    <div class="border-b mb-2 flex justify-between px-4 py-5 sm:px-6 align-middle">
        <div class="flex">
            <h3 class="m-auto text-lg leading-6 text-gray-900">
                {{ $application->firstname }} {{ $application->name }}
                <span title="{{ $application->id }}" class="font-mono text-xs">{{ $application->getShortenedId() }}</span>
            </h3>
        </div>
        <div class="flex items-baseline flex-wrap">
            <p class="mx-1">
                    {{ ucfirst(__("dashboard.status.new", ['timeDiff' => $application->created_at->diffForHumans()])) }}
                @if($application->status->value !== 'new')
                    et {{ __("dashboard.status.{$application->status->value}", ['timeDiff' => $application->updated_at->diffForHumans()]) }}.
                @endif

            </p>

            <div class="flex flex-wrap">
                @if($canDone)
                    <form wire:submit="done" class="mx-1">
                        <input class="form__submit w-full my-1 md:w-auto" type="submit" value="{{$doneName}}" />
                    </form>
                @endif
                @if($canUndo)
                    <form wire:submit="undo" class="mx-1">
                        <button class="form__submit w-full my-1 md:w-auto" wire:click.prevent="$set('confirmUndo', true)">Remettre à "{{ __('dashboard.todo.'.$application->status->prev()->value)}}"</button>
                    </form>
                @endif
                @if($canReject)
                    <form wire:submit="reject" class="mx-1">
                        <input class="form__submit form__submit_error w-full my-1 md:w-auto" type="submit" value="{{ __('dashboard.actions.reject') }}" />
                    </form>
                @endif
            </div>
        </div>
    </div>

    <livewire:application-overview :application="$application" :showRestrictedInformation="true" />

    @if ($canUndo)
    <x-confirmation-modal wire:model.live="confirmUndo">
        <x-slot name="title">
        Revenir en arrière ({{ $application->firstname }} {{ $application->name }})
        </x-slot>

        <x-slot name="content">
        Êtes-vous sûr de vouloir remettre cette adhésion dans "{{ __('dashboard.todo.'.$application->status->prev()->value)}}" ?
        </x-slot>

        <x-slot name="footer">
        <x-secondary-button wire:click="$toggle('confirmUndo')" wire:loading.attr="disabled">
            Non
        </x-secondary-button>

        <x-button class="ml-2" wire:click="undo" wire:loading.attr="disabled">
            Oui
        </x-button>
        </x-slot>
    </x-confirmation-modal>
    @endif
</div>

resources/views/livewire/show-applications.blade.php
<section>
    <p class="text-xl">
        {{ $title }}
    </p>
    <p>
        {{ $subtitle }}
    </p>

    <div class="max-w-7xl mx-auto sm:p-6 lg:p-8">
        @if($applications->count() === 0)
            <p>{{ __('dashboard.no_applications_found') }}</p>
        @endif

        @foreach ($applications as $application)
            <livewire:show-application :application="$application" wire:key="{{ $application->id }}" />
        @endforeach
    </div>
</section>

resources/views/livewire/signature-input.blade.php
<div class="form__input-group">
    <div class="form__input-group__element">
        @if($signatureFile === null)
            <label class="form__input-group__element__label" for="signature">
                Dessinez votre signature
            </label>
            <canvas
                id="signature-freehand"
                class="form__input-group__element__input border-black bg-white max-w-md !p-0 !hidden"
                style="height: 100px; width: 300px"
                width="300px"
                height="100px"
            >
                Votre navigateur ne supporte pas la technologie canvas, téléversez un scan de votre signature <label for="signature-file" class="cursor-pointer underline">en cliquant ici</label>.
            </canvas>
            <button id="reset-signature" class="form__submit_white my-2 hidden">Effacer</button>
        @endif

        <label>
            <span class="form__input-group__element__label">En cas d'impossibilité, téléversez votre signature</span> (PNG et JPG, maximum 200 kilo-octets)
            <input type="file" wire:model="signatureFile">
        </label>
    </div>
</div>